version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: gst-invoices-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: gst_invoices
      POSTGRES_USER: gst_user
      POSTGRES_PASSWORD: gst_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - gst-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: gst-invoices-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gstinvoices.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - gst-network

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  gst-network:
    driver: bridge
